language: python
python:
- 3.5
services:
- docker
before_install:
- docker network create dvs
- export NETWORK_INTERFACE_NAME=$(route | grep '^default' | grep -o '[^ ]*$')
- export NETWORK_INTERFACE_ADDRESS=$(ip addr show $NETWORK_INTERFACE_NAME | grep -Po 'inet \K[\d.]+')
- docker-compose -f ci/compose/aesel/docker-compose.yml up &
- sleep 480
- docker ps -a
- npm install newman --global;
install:
- pip install -r requirements.txt
script:
- cd $TRAVIS_BUILD_DIR && python -m pytest
- docker stop $(docker ps -aq)
- docker rm $(docker ps -aq)
